Repository alloy-rs/evm, pull requests merged in 2025-05, with the labels that each got.

#83 fix: use HashMap::with_capacity_and_hasher
  crates/evm/src/block/state_changes.rs
  crates/evm/src/precompiles.rs
Labels: bug

#81 feat: expose Inspector on Evm
  crates/evm/src/eth/mod.rs
  crates/evm/src/evm.rs
  crates/op-evm/src/lib.rs
Labels: enhancement

#86 fix: `r.as_ref()` the trait `AsRef<[_; 0]>` is not implemented for `[u8]`
  crates/evm/src/precompiles.rs
Labels: bug

#91 chore: preparing for mint nonoptional in reth
  Cargo.toml
  crates/evm/src/tx.rs
Labels: blocked
